### ISSUE TITLE
AttributeError exception occurred when trying to generate doc by sphinx

### ISSUE THREAD

**Issue by shgharib** [stefanfoulis/django-phonenumber-field#109]
5:17 PM
/vagrant/docs/reference/core/accounting.rst:29: WARNING: autodoc: failed to import attribute 'BaseProfile.phone_number' from module 'app_server.apps.core.accounting.models'; the following exception was raised:
Traceback (most recent call last):
File "/home/vagrant/.virtualenvs/app_server/lib/python3.4/site-packages/sphinx/util/inspect.py", line 109, in safe_getattr
return getattr(obj, name, *defargs)
File "/home/vagrant/.virtualenvs/app_server/lib/python3.4/site-packages/phonenumber_field/modelfields.py", line 33, in __get__
% (self.field.name, owner.__name__))
AttributeError: The 'phone_number' attribu
te can only be accessed from BaseProfile instances.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/app_server/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 392, in import_object
    obj = self.get_attr(obj, part)
  File "/home/vagrant/.virtualenvs/app_server/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 288, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/home/vagrant/.virtualenvs/app_server/lib/python3.4/site-packages/sphinx/util/inspect.py", line 115, in safe_getattr
    raise AttributeError(name)
AttributeError: phone_number
/vagrant/docs/reference/core/accounting.rst:29: WARNING: autodoc: failed to import attribute 'LegalProfile.phone_number' from module 'app_server.apps.core.accounting.models'; the following exception was raised:
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/app_server/lib/python3.4/site-packages/sphinx/util/inspect.py", line 109, in safe_getattr
    return getattr(obj, name, *defargs)
  File "/home/vagrant/.virtualenvs/app_server/lib/python3.4/site-packages/phonenumber_field/modelfields.py", line 33, in __get__
    % (self.field.name, owner.__name__))
AttributeError: The 'phone_number' attribute can only be accessed from LegalProfile instances.

**Comment by amateja** [comment]
Thank you for reporting but it looks like you are using PhoneNumberField in some odd way. You didn't share much details. Are you sure that this problem lies here?

**Comment by amateja** [comment]
Thank you for reporting. Our project has evolved since that time and this issue will be closed. Please update and reopen if you feel it is still applicable.
