### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'widget'

### ISSUE THREAD

**Issue by rauleb** [stefanfoulis/django-phonenumber-field#148]
I got this error when y use the widget in the form in this form
`telefono = PhoneNumberField(widget=PhoneNumberPrefixWidget)`
This way worked, but no longer works. What is the new way?

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10457a268>
Traceback (most recent call last):
  File "/Users/raulburro/Documents/Softec/Frodent/frodent/env/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/raulburro/Documents/Softec/Frodent/frodent/env/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "/Users/raulburro/Documents/Softec/Frodent/frodent/env/lib/python3.5/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/raulburro/Documents/Softec/Frodent/frodent/env/lib/python3.5/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/raulburro/Documents/Softec/Frodent/frodent/env/lib/python3.5/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/Users/raulburro/Documents/Softec/Frodent/frodent/env/lib/python3.5/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    for pattern in resolver.url_patterns:
  File "/Users/raulburro/Documents/Softec/Frodent/frodent/env/lib/python3.5/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/raulburro/Documents/Softec/Frodent/frodent/env/lib/python3.5/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/raulburro/Documents/Softec/Frodent/frodent/env/lib/python3.5/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/raulburro/Documents/Softec/Frodent/frodent/env/lib/python3.5/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/raulburro/Documents/Softec/Frodent/frodent/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/raulburro/Documents/Softec/Frodent/frodent/frodent/urls.py", line 21, in <module>
    from frodent_app.views import DashboardView
  File "/Users/raulburro/Documents/Softec/Frodent/frodent/frodent_app/views.py", line 22, in <module>
    from clinica_app.forms import ProcedimientoForm
  File "/Users/raulburro/Documents/Softec/Frodent/frodent/clinica_app/forms.py", line 208, in <module>
    class PacienteForm(MaterializeFormMixin, forms.ModelForm):
  File "/Users/raulburro/Documents/Softec/Frodent/frodent/clinica_app/forms.py", line 211, in PacienteForm
    telefono = PhoneNumberField(widget=PhoneNumberPrefixWidget)  # widget=PhoneNumberPrefixWidget khe?
  File "/Users/raulburro/Documents/Softec/Frodent/frodent/env/lib/python3.5/site-packages/phonenumber_field/modelfields.py", line 51, in __init__
    super(PhoneNumberField, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'widget'
```

**Comment by tredzko** [comment]
Based on:
```
  File "/Users/raulburro/Documents/Softec/Frodent/frodent/env/lib/python3.5/site-packages/phonenumber_field/modelfields.py", line 51, in __init__
```
It looks like you're importing the `model` field instead of the `form` field. Wherever you're importing `PhoneNumberField` for your form, verify that it is importing from `formfields`:

```
from phonenumber_field.formfields import PhoneNumberField
```

The reason you were getting this error is that `widget`s are part of form fields in Django. The form `PhoneNumberField` is based on `CharField`. The `modelfield`, which I believe you are currently importing, is for use on models and would not have a `widget` attribute.
