### ISSUE TITLE
`python setup.py test` fails

### ISSUE THREAD

**Issue by ncopa** [stefanfoulis/django-phonenumber-field#213]
When packaging alpine linux packages we run tests if there are any available. Most python packages can be tested with `python setup.py test`, but django-phonenumber-field fails:

````
$ python setup.py test
running test
running egg_info
writing requirements to django_phonenumber_field.egg-info/requires.txt
writing django_phonenumber_field.egg-info/PKG-INFO
writing top-level names to django_phonenumber_field.egg-info/top_level.txt
writing dependency_links to django_phonenumber_field.egg-info/dependency_links.txt
reading manifest file 'django_phonenumber_field.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'django_phonenumber_field.egg-info/SOURCES.txt'
running build_ext
phonenumber_field.tests (unittest.loader.ModuleImportFailure) ... ERROR

======================================================================
ERROR: phonenumber_field.tests (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: phonenumber_field.tests
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/ncopa/aports/main/py-django-phonenumber-field/src/django-phonenumber-field-1.3.0/phonenumber_field/tests.py", line 19, in <module>
    class MandatoryPhoneNumber(models.Model):
  File "/home/ncopa/aports/main/py-django-phonenumber-field/src/django-phonenumber-field-1.3.0/phonenumber_field/tests.py", line 20, in MandatoryPhoneNumber
    phone_number = PhoneNumberField()
  File "/home/ncopa/aports/main/py-django-phonenumber-field/src/django-phonenumber-field-1.3.0/phonenumber_field/modelfields.py", line 50, in __init__
    super(PhoneNumberField, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 172, in __init__
    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 39, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
ImproperlyConfigured: Requested setting DEFAULT_INDEX_TABLESPACE, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
````

**Comment by jdufresne** [comment]
`python setup.py test` is not supported to run tests. Please use `tox` instead.
