### ISSUE TITLE
Failed to add phonenumber from django admin

### ISSUE THREAD

**Issue by waryak** [stefanfoulis/django-phonenumber-field#367]
`    phone_number = PhoneNumberField(help_text='Contact phone number', unique=True)
`
resulted in

`Traceback (most recent call last):
  File "/Users/waryak/.virtualenvs/python3.8_django/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/waryak/.virtualenvs/python3.8_django/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/waryak/.virtualenvs/python3.8_django/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/waryak/.virtualenvs/python3.8_django/lib/python3.8/site-packages/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/waryak/.virtualenvs/python3.8_django/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/waryak/.virtualenvs/python3.8_django/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/waryak/.virtualenvs/python3.8_django/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/Users/waryak/.virtualenvs/python3.8_django/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1638, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/waryak/.virtualenvs/python3.8_django/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/waryak/.virtualenvs/python3.8_django/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/waryak/.virtualenvs/python3.8_django/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/Users/waryak/.virtualenvs/python3.8_django/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1569, in _changeform_view
    self.log_addition(request, new_object, change_message)
  File "/Users/waryak/.virtualenvs/python3.8_django/lib/python3.8/site-packages/django/contrib/admin/options.py", line 807, in log_addition
    object_repr=str(object),
TypeError: __str__ returned non-string (type PhoneNumber)`

**Comment by francoisfreitag** [comment]
I can see the phone number field in my admin and can save a value to it without errors. `PhoneNumber` objects can be represented with an `__str__`, at least on the latest version.

If you can reproduce the issue, can you share a test case or a minimal project that shows the issue?

**Comment by amateja** [comment]
I've come up with idea how this could happen.

```pycon
>>> import phonenumbers
>>> from phonenumber_field.phonenumber import PhoneNumber
>>> 
>>> us = phonenumbers.example_number(region_code='US')
>>> fake = PhoneNumber()
>>> fake.raw_input = us
>>> str(fake)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __str__ returned non-string (type PhoneNumber)
```

Currently this only can occur if someone tampers with `PhoneNumber.raw_input`. In reported traceback it looks like `raw_input` is type of `PhoneNumber` but should be string instead.

In our code this property is set in one location - in `to_python` function ([here](https://github.com/stefanfoulis/django-phonenumber-field/blob/main/phonenumber_field/phonenumber.py#L140)) only if it is instance of `str`. Therefore it doesn't look like our library is breaking this down. To say more as François wrote we need some code snippet.
