### ISSUE TITLE
Default error message in formfields.PhoneNumberField causes AppRegistryNotReady error

### ISSUE THREAD

**Issue by traviselam** [stefanfoulis/django-phonenumber-field#436]
```
/server/venv/bin/python /server/src/forms.py
Traceback (most recent call last):
  File "/server/venv/lib/python3.8/site-packages/django/utils/translation/trans_real.py", line 194, in _add_installed_apps_translations
    app_configs = reversed(list(apps.get_app_configs()))
  File "/server/venv/lib/python3.8/site-packages/django/apps/registry.py", line 145, in get_app_configs
    self.check_apps_ready()
  File "/server/venv/lib/python3.8/site-packages/django/apps/registry.py", line 136, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/server/src/forms.py", line 11, in <module>
    class RegisterForm(forms.Form):
  File "/server/src/forms.py", line 33, in RegisterForm
    phone_number = PhoneNumberField()
  File "/server/venv/lib/python3.8/site-packages/phonenumber_field/formfields.py", line 34, in __init__
    self.error_messages["invalid"] = error_message.format(
  File "/server/venv/lib/python3.8/site-packages/django/utils/functional.py", line 135, in __wrapper__
    res = func(*self.__args, **self.__kw)
  File "/server/venv/lib/python3.8/site-packages/django/utils/translation/__init__.py", line 94, in gettext
    return _trans.gettext(message)
  File "/server/venv/lib/python3.8/site-packages/django/utils/translation/trans_real.py", line 355, in gettext
    _default = _default or translation(settings.LANGUAGE_CODE)
  File "/server/venv/lib/python3.8/site-packages/django/utils/translation/trans_real.py", line 268, in translation
    _translations[language] = DjangoTranslation(language)
  File "/server/venv/lib/python3.8/site-packages/django/utils/translation/trans_real.py", line 155, in __init__
    self._add_installed_apps_translations()
  File "/server/venv/lib/python3.8/site-packages/django/utils/translation/trans_real.py", line 196, in _add_installed_apps_translations
    raise AppRegistryNotReady(
django.core.exceptions.AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time.

Process finished with exit code 1

```

I have the following in my django settings file:

```
from django.utils.translation import ugettext_lazy as _

USE_I18N = True

USE_L10N = True

LANGUAGE_CODE = 'en-us'

LANGUAGES = [
    ('en', _('English'))
]
```

I also have a forms.py file with my form that contains the PhoneNumberField class. At the bottom of that file I have a standard main with some test code and upon running that I get the following error above because the PhoneNumberField class is attempting to load the app registry upon import. I believe this form field should lazy load when used with internationalization. If I am missing something please point me in the right direction and close the issue. This is my first time using this package.

**Comment by francoisfreitag** [comment]
Hi, thanks for reporting!

Does your main call `django.setup()`? That should populate the application registry.
https://docs.djangoproject.com/en/3.2/topics/settings/#calling-django-setup-is-required-for-standalone-django-usage

**Comment by traviselam** [comment]
Of course! And yes I do at the bottom of the file. But in Django 3.2 the form.Form class uses declarative fields. And when adding the PhoneNumberField to my custom form it attempts to initialize the Django apps on import even if I'm not running the file directly. It never reaches my django.setup() call at the bottom main and breaks when importing other things from the same file.

**Comment by francoisfreitag** [comment]
Right. `django.setup()` needs to be called before you import the forms module entirely.

I would not recommend writing your tests at the bottom of the forms module, as if it were a standalone module. The forms module needs django to be setup.

For example, importing from the models will raise:
```python
# Code
from django import forms

from bar.models import Foo

class MyModelForm(forms.ModelForm):
    class Meta:
        model = Foo
        fields = ['name']

if __name__ == "__main__":
    "Write tests"

# Running python myapp/forms.py
Traceback (most recent call last):
  File "/tmp/tmp.AofZRIY8gw/foo/bar/forms.py", line 5, in <module>
    from bar.models import Foo
  File "/tmp/tmp.AofZRIY8gw/foo/bar/models.py", line 4, in <module>
    class Foo(models.Model):
  File "/tmp/tmp.AofZRIY8gw/venv/lib/python3.9/site-packages/django/db/models/base.py", line 108, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/tmp/tmp.AofZRIY8gw/venv/lib/python3.9/site-packages/django/apps/registry.py", line 253, in get_containing_app_config
    self.check_apps_ready()
  File "/tmp/tmp.AofZRIY8gw/venv/lib/python3.9/site-packages/django/apps/registry.py", line 136, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

Django has a bootstrap procedure for tests (`python -m django test ...`), I recommend using it.
That being said, looking at Django source code, all form fields error messages are indeed translated with `gettext_lazy`. This library should follow.

**Comment by traviselam** [comment]
@francoisfreitag thank you for the information regarding the django test. And I'm glad you took a look at the Django source code. That was why I reported the "bug" in the first place. I noticed their code was lazy translating their messages and I figured this library should follow as well. Without lazy loading anything that would use some of your default classes that get initialized on import would cause the error that I reported. Thanks again for the quick response!
