### ISSUE TITLE
Missing dependancies

### ISSUE THREAD

**Issue by chrispydev** [stefanfoulis/django-phonenumber-field#494]
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/christian/Desktop/code/projects/attendancebackend/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/christian/Desktop/code/projects/attendancebackend/venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/home/christian/Desktop/code/projects/attendancebackend/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/christian/Desktop/code/projects/attendancebackend/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 398, in execute
    autoreload.check_errors(django.setup)()
  File "/home/christian/Desktop/code/projects/attendancebackend/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/christian/Desktop/code/projects/attendancebackend/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/christian/Desktop/code/projects/attendancebackend/venv/lib/python3.10/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/home/christian/Desktop/code/projects/attendancebackend/venv/lib/python3.10/site-packages/django/apps/config.py", line 304, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/christian/Desktop/code/projects/attendancebackend/backend/users/models.py", line 6, in <module>
    from phonenumber_field.modelfields import PhoneNumberField
  File "/home/christian/Desktop/code/projects/attendancebackend/venv/lib/python3.10/site-packages/phonenumber_field/modelfields.py", line 7, in <module>
    from phonenumber_field import formfields
  File "/home/christian/Desktop/code/projects/attendancebackend/venv/lib/python3.10/site-packages/phonenumber_field/formfields.py", line 1, in <module>
    import phonenumbers
ModuleNotFoundError: No module named 'phonenumbers'

**Comment by francoisfreitag** [comment]
Hi,
You need to specify what version of the phonenumbers library you need on install. See https://github.com/stefanfoulis/django-phonenumber-field#installation.
