### ISSUE TITLE
django-phonenumber-field[phonenumberslite] requires phonenumbers on migration

### ISSUE THREAD

**Issue by davidtingsu** [stefanfoulis/django-phonenumber-field#608]
I installed django-phonenumber-field with phonenumberslite and when I ran the migration I got No module named phonenumbers. My work around was just to install `phonenumbers`

Reproduction steps:

```
poetry add "django-phonenumber-field[phonenumberslite]"
poetry shell
```

```
 python manage.py makemigrations
 

 Traceback (most recent call last):
  File "/Users/davidsu/myproject/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/davidsu/.pyenv/versions/3.11.7/lib/python3.11/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/Users/davidsu/.pyenv/versions/3.11.7/lib/python3.11/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/Users/davidsu/.pyenv/versions/3.11.7/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/davidsu/.pyenv/versions/3.11.7/lib/python3.11/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/davidsu/.pyenv/versions/3.11.7/lib/python3.11/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidsu/.pyenv/versions/3.11.7/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/davidsu/myproject/patients/models/__init__.py", line 14, in <module>
    from .provider import Provider
  File "/Users/davidsu/myproject/patients/models/provider.py", line 4, in <module>
    from phonenumber_field.modelfields import PhoneNumberField
  File "/Users/davidsu/.pyenv/versions/3.11.7/lib/python3.11/site-packages/phonenumber_field/modelfields.py", line 7, in <module>
    from phonenumber_field import formfields
  File "/Users/davidsu/.pyenv/versions/3.11.7/lib/python3.11/site-packages/phonenumber_field/formfields.py", line 1, in <module>
    import phonenumbers
ModuleNotFoundError: No module named 'phonenumbers'
Sentry is attempting to send 2 pending events
```

**Comment by francoisfreitag** [comment]
`phonenumberslite` provides the phonenumbers package.


```sh
/tmp/tmp.917HyAMRa2 % python -m venv venv
/tmp/tmp.917HyAMRa2 % . venv/bin/activate
(venv) /tmp/tmp.917HyAMRa2 % pip install phonenumberslite
Collecting phonenumberslite
  Downloading phonenumberslite-8.13.39-py2.py3-none-any.whl.metadata (11 kB)
Downloading phonenumberslite-8.13.39-py2.py3-none-any.whl (470 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 470.6/470.6 kB 8.8 MB/s eta 0:00:00
Installing collected packages: phonenumberslite
Successfully installed phonenumberslite-8.13.39

[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: pip install --upgrade pip
(venv) /tmp/tmp.917HyAMRa2 % python
Python 3.12.4 (main, Jun  7 2024, 06:33:07) [GCC 14.1.1 20240522] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import phonenumbers
>>>
```

I think your issue is that `phonenumberlite` was not installed in the environment running the migrations (or the venv not activated).
